### ISSUE TITLE
Xcomfort Node-red

### ISSUE THREAD

**Issue by MMB22-hash** [oanylund/xcomfort-shc-api#2]
Hello,

Can you implement xcomfort-shc-api in node-red?
Or at least can you help me using xcomfort in node-red?

Thanks.

**Comment by oanylund** [comment]
Hi!

The development of this repo is not active as i do not own a Xcomfort system anymore and do not have any way to verify new features against a system. 

Have you tested that this library still works against the newest updates for the smart hub? If so then creating a wrapper for this library to node-red should not be that hard to implement.

**Comment by MMB22-hash** [comment]
Hello,

Thanks for your reply. I have not tested due to the fact that i do not 
know java and i'm not a programmer.

I do know how to work with node-red due it's simplicity but further more no.

I will try to test it by reading some tutorial but i don't know from 
where to start.

Thank you for your support.

Regards,

**Comment by oanylund** [comment]
Hi again,

I see, then i would suggest trying the library running as a plain server first. It's actually not java but javascript(node.js)
To test it locally requires little experience.

1. Install [node.js](https://nodejs.org/en/) on you machine
2. Create a folder for your project
3. Create a file in your folder named x.js (x can be anything)
4. Follow the steps [here](https://oanylund.github.io/xcomfort-shc-api/) to create a script for your system
5. Run `npm install` in the terminal
6. Run `node x.js` where x is whatever you called the file you created earlier

I think that should get you close. If you hit a wall with node.js google is your friend. There is a lot of good content on the subject out there.
